name: keystone
description: Aplicação para outorga de recursos hídricos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0

  flutter:
    sdk: flutter

  flutter_barcode_scanner: ^2.0.0
  flutter_speed_dial: ^4.3.0

  # https://github.com/edufolly/folly_fields
  folly_fields:
    git:
      url: git://github.com/edufolly/folly_fields.git
      rev: 0.3.1

  math_expressions: ^2.2.0
  pdf: ^3.6.0
  printing: ^5.6.0
  qr_flutter: ^4.0.0

dev_dependencies:
  firebase_auth_mocks: ^0.8.1
  fake_cloud_firestore: ^1.1.3

  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  mocktail: ^0.1.4

  test: any


flutter:
  uses-material-design: true
